"""Permissible free dairy-information sources and collection guidance."""

SOURCE_CATALOG = (
    {
        "name": "FAOSTAT",
        "tier": "International official statistics",
        "categories": ("production", "livestock", "consumption", "trade"),
        "url": "https://www.fao.org/faostat/",
        "use": "Automated official bulk/API imports supported through Market Opportunities.",
    },
    {
        "name": "UN Comtrade",
        "tier": "International official trade statistics",
        "categories": ("imports", "exports", "trade_partners"),
        "url": "https://comtradeplus.un.org/",
        "use": "Automated annual HS trade imports supported through Market Opportunities; public API rate limits apply.",
    },
    {
        "name": "World Bank Open Data",
        "tier": "International official development statistics",
        "categories": ("economic_indicators", "population", "urbanization"),
        "url": "https://data.worldbank.org/",
        "use": "Automated population, GDP, urbanization, inflation, and GDP-per-capita imports are supported.",
    },
    {
        "name": "NASA POWER",
        "tier": "Government satellite-derived climate data",
        "categories": ("climate",),
        "url": "https://power.larc.nasa.gov/",
        "use": "Automated country-coordinate temperature and precipitation context is supported; it is not farm-level weather data.",
    },
    {
        "name": "USDA Foreign Agricultural Service",
        "tier": "Government agricultural intelligence",
        "categories": ("production", "trade", "policies", "market_trends", "forecast"),
        "url": "https://www.fas.usda.gov/data",
        "use": "Import published country reports and datasets only where public terms permit; retain report URL and data year.",
    },
    {
        "name": "OECD Data Explorer",
        "tier": "International official statistics",
        "categories": ("prices", "production", "economic_indicators", "policies"),
        "url": "https://data-explorer.oecd.org/",
        "use": "Use downloadable or API-accessible datasets and cite the exact table or record URL.",
    },
    {
        "name": "IMF Data",
        "tier": "International official macroeconomic statistics",
        "categories": ("inflation", "exchange_rates", "economic_indicators"),
        "url": "https://data.imf.org/",
        "use": "Use public datasets where terms permit and retain the series URL/year.",
    },
    {
        "name": "WOAH",
        "tier": "Intergovernmental animal-health information",
        "categories": ("disease", "veterinary"),
        "url": "https://www.woah.org/",
        "use": "Use public animal-health reports and cite publication/record URLs.",
    },
    {
        "name": "National ministries, statistics offices, and open-data portals",
        "tier": "National official data",
        "categories": ("production", "farms", "companies", "policies", "prices", "feed", "employment"),
        "url": "",
        "use": "Download or cite public files where permitted; do not automate CAPTCHA, authentication-gated, or prohibited sites.",
    },
    {
        "name": "Dairy associations, cooperatives, and company reports",
        "tier": "Reputable secondary / primary corporate publication",
        "categories": ("companies", "cooperatives", "processing", "brands", "investment", "sustainability"),
        "url": "",
        "use": "Use publicly published reports/annual reports only; mark source tier and retain canonical URL.",
    },
    {
        "name": "Academic and university publications",
        "tier": "Research publication",
        "categories": ("research", "technology", "consumer_trends", "climate", "feed"),
        "url": "https://scholar.google.com/",
        "use": "Capture a citation and source URL; do not reproduce copyrighted report content.",
    },
)

EVIDENCE_CATEGORIES = (
    "production",
    "consumption",
    "demand",
    "livestock",
    "farms",
    "processing",
    "products",
    "imports",
    "exports",
    "trade_partners",
    "trade",
    "prices",
    "economic_indicators",
    "population",
    "urbanization",
    "feed",
    "veterinary",
    "disease",
    "climate",
    "companies",
    "cooperatives",
    "brands",
    "employment",
    "policies",
    "subsidies",
    "consumer_trends",
    "technology",
    "cold_chain",
    "investment",
    "forecast",
    "research",
)
